import type { CompanyProfile, CurrencyCode } from './types';

export const mapApiToCompanyProfile = (
  data: Record<string, unknown>,
  overrides?: Partial<CompanyProfile>,
): CompanyProfile => ({
  companyName: String(data.companyName || data.name || ''),
  ticker: String(data.ticker || data.symbol || ''),
  currency: (overrides?.currency as CurrencyCode) || 'USD',
  industry: String(overrides?.industry || data.industry || ''),
  region: String(overrides?.region || data.region || data.country || ''),
  stockPrice: Number(data.currentPrice ?? data.stockPrice ?? data.price ?? 0),
  marketCap: Number(data.marketCap ?? data.mktCap ?? 0),
  sharesOutstanding: Number(data.sharesOutstanding ?? 0),
  revenue: Number(data.revenue ?? 0),
  ebitda: Number(data.ebitda ?? 0),
  ebit: Number(data.ebit ?? data.operatingIncome ?? 0),
  netIncome: Number(data.netIncome ?? 0),
  cash: Number(data.cash ?? data.cashAndCashEquivalents ?? 0),
  debt: Number(data.debt ?? data.totalDebt ?? 0),
  workingCapital: Number(data.workingCapital ?? 0),
  freeCashFlow: Number(data.freeCashFlow ?? 0),
  capex: Number(Math.abs(Number(data.capex ?? 0))),
  depreciationAndAmortization: Number(data.depreciationAndAmortization ?? 0),
  historicalRevenueGrowth: Number(data.historicalRevenueGrowth ?? data.revenueGrowth ?? 5),
  historicalEbitdaMargin: Number(data.historicalEbitdaMargin ?? 20),
  historicalEbitMargin: Number(data.historicalEbitMargin ?? 15),
  historicalFcfMargin: Number(data.historicalFcfMargin ?? 10),
  ...overrides,
});

export const companyProfileToDcfPayload = (profile: CompanyProfile) => ({
  companyName: profile.companyName,
  ticker: profile.ticker,
  currentPrice: profile.stockPrice,
  marketCap: profile.marketCap,
  sharesOutstanding: profile.sharesOutstanding,
  revenue: profile.revenue,
  ebitda: profile.ebitda,
  ebit: profile.ebit,
  netIncome: profile.netIncome,
  cash: profile.cash,
  debt: profile.debt,
  workingCapital: profile.workingCapital,
  freeCashFlow: profile.freeCashFlow,
  capex: profile.capex,
  depreciationAndAmortization: profile.depreciationAndAmortization,
  historicalRevenueGrowth: profile.historicalRevenueGrowth,
  historicalEbitdaMargin: profile.historicalEbitdaMargin,
  historicalEbitMargin: profile.historicalEbitMargin,
  historicalFcfMargin: profile.historicalFcfMargin,
});
