export const valuationModels = [
  {
    title: 'Discounted Cash Flow (DCF)',
    shortTitle: 'DCF',
    tagline: 'Intrinsic value from cash flow durability.',
    description: 'A 10-year free cash flow engine with discounting, terminal value, scenario ranges, and sensitivity analysis.',
    formulas: ['EV = PV(FCF) + PV(Terminal Value)', 'Equity Value = EV + Cash - Debt'],
    scenarios: ['Bear Case', 'Base Case', 'Bull Case'],
    useCases: ['Long-term compounders', 'cash generative businesses', 'margin expansion theses'],
    outputs: ['Enterprise value', 'equity value', 'fair value per share', 'margin of safety'],
    accent: '#4F8CFF',
    href: '/models/dcf',
  },
  {
    title: 'Comparable Company Analysis',
    shortTitle: 'Comps',
    tagline: 'Market-implied valuation benchmarking.',
    description: 'Peer multiple comparison across revenue, EBITDA, earnings, and implied valuation range outputs.',
    formulas: ['EV = EBITDA x Peer Multiple', 'Share Price = Equity Value / Shares'],
    scenarios: ['Conservative', 'Base', 'Premium'],
    useCases: ['Public peers', 'sector valuation ranges', 'IPO and transaction screening'],
    outputs: ['Implied EV', 'implied share price', 'valuation range'],
    accent: '#00C896',
    href: '/models/comps',
  },
  {
    title: 'Dividend Discount Model',
    shortTitle: 'DDM',
    tagline: 'Income valuation for durable payouts.',
    description: 'Dividend growth and cost of equity model for stable payout profiles and yield-sensitive equities.',
    formulas: ['Value = D1 / (r - g)', 'D1 = DPS x (1 + g)'],
    scenarios: ['Low Growth', 'Stable Growth', 'High Growth'],
    useCases: ['Banks', 'utilities', 'mature cash return stories'],
    outputs: ['Intrinsic value', 'dividend forecast', 'valuation sensitivity'],
    accent: '#F5B942',
    href: '/models/ddm',
  },
  {
    title: 'Residual Income Model',
    shortTitle: 'RIM',
    tagline: 'Value creation above book equity.',
    description: 'Equity value framework that capitalizes residual earnings generated above required shareholder returns.',
    formulas: ['Value = Book Value + PV(Residual Income)', 'RI = Net Income - Equity Charge'],
    scenarios: ['Mean Reversion', 'Base ROE', 'Premium ROE'],
    useCases: ['Financial institutions', 'book-value driven equities', 'ROE normalization'],
    outputs: ['Equity value', 'residual income bridge', 'ROE sensitivity'],
    accent: '#8FB3FF',
    href: '/models/rim',
  },
  {
    title: 'Precedent Transactions',
    shortTitle: 'Precedents',
    tagline: 'Control-premium transaction benchmarking.',
    description: 'Deal multiple analysis across announced transactions, premiums paid, and implied acquisition value ranges.',
    formulas: ['Implied EV = Metric x Transaction Multiple', 'Premium = Offer Price / Unaffected Price - 1'],
    scenarios: ['Strategic Buyer', 'Financial Sponsor', 'Scarcity Premium'],
    useCases: ['M&A valuation', 'fairness analysis', 'take-private screening'],
    outputs: ['Transaction range', 'premium paid', 'control value'],
    accent: '#FF7A90',
    href: '/models/precedent',
  },
  {
    title: 'Leveraged Buyout (LBO)',
    shortTitle: 'LBO',
    tagline: 'Sponsor return and capital structure model.',
    description: 'Debt schedule, exit multiple, cash sweep, and sponsor IRR analysis for acquisition underwriting.',
    formulas: ['IRR = Sponsor Exit Equity / Entry Equity', 'Debt Paydown = FCF - Interest'],
    scenarios: ['Downside Exit', 'Base Exit', 'Upside Exit'],
    useCases: ['Sponsor deals', 'take-private screens', 'capital structure stress tests'],
    outputs: ['Sponsor IRR', 'MOIC', 'debt paydown', 'exit equity value'],
    accent: '#7C5CFF',
    href: '/models/lbo',
  },
  {
    title: 'Sum-of-the-Parts (SOTP)',
    shortTitle: 'SOTP',
    tagline: 'Segment-level enterprise value decomposition.',
    description: 'Multi-segment valuation framework for conglomerates, holdcos, and businesses with distinct growth profiles.',
    formulas: ['Total EV = Sum(Segment EV)', 'Equity Value = Total EV + Net Cash'],
    scenarios: ['Discounted Holdco', 'Base Segments', 'Unlock Case'],
    useCases: ['Conglomerates', 'spin-offs', 'segment valuation debates'],
    outputs: ['Segment value bridge', 'holdco discount', 'per-share NAV'],
    accent: '#00C2FF',
    href: '/models/sotp',
  },
  {
    title: 'Economic Value Added (EVA)',
    shortTitle: 'EVA',
    tagline: 'Capital efficiency and value creation analysis.',
    description: 'Measures economic profit after capital charges to determine whether growth creates or destroys value.',
    formulas: ['EVA = NOPAT - Capital Charge', 'Capital Charge = Invested Capital x WACC'],
    scenarios: ['Efficiency Reset', 'Base NOPAT', 'Reinvestment Case'],
    useCases: ['Industrial businesses', 'capital allocators', 'margin and ROIC studies'],
    outputs: ['EVA bridge', 'invested capital returns', 'ROIC spread'],
    accent: '#00E5A8',
    href: '/models/eva',
  },
  {
    title: 'Quantitative Factor Engine',
    shortTitle: 'Factors',
    tagline: 'Multi-factor scoring for security selection.',
    description: 'Composite factor model across value, quality, momentum, growth, volatility, and balance sheet strength.',
    formulas: ['Score = Weighted Sum(Factor Z-Scores)', 'Rank = Percentile(Security Score)'],
    scenarios: ['Quality Tilt', 'Value Tilt', 'Momentum Tilt'],
    useCases: ['Screening', 'factor research', 'portfolio construction'],
    outputs: ['Composite score', 'factor ranks', 'screened universe'],
    accent: '#7C5CFF',
    href: '/models/factors',
  },
];
